// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SampleApp {
	
	
	public partial class _Person {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Label lblName;
		
		protected System.Web.UI.WebControls.TextBox txtName;
		
		protected System.Web.UI.WebControls.Label lblEmail;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.CheckBoxList cblDepartments;
		
		protected System.Web.UI.WebControls.DropDownList cmbCategory;
		
		protected System.Web.UI.WebControls.CheckBoxList cblItems;
		
		protected System.Web.UI.WebControls.CheckBox chkActive;
		
		protected System.Web.UI.WebControls.DropDownList cmbMaritalStatus;
		
		protected System.Web.UI.WebControls.DropDownList cmbContractType;
		
		protected System.Web.UI.WebControls.Label lblPhoto;
		
		protected System.Web.UI.WebControls.FileUpload fupPhoto;
		
		protected System.Web.UI.WebControls.Button btnSave;
	}
}
