// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SampleApp {
	
	
	public partial class PersonList {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Panel pnlSearch;
		
		protected System.Web.UI.WebControls.TextBox txtName;
		
		protected System.Web.UI.WebControls.TextBox txtItemName;
		
		protected System.Web.UI.WebControls.TextBox txtCategory;
		
		protected System.Web.UI.WebControls.Button btnSearch;
		
		protected System.Web.UI.WebControls.Panel pnlResults;
		
		protected System.Web.UI.WebControls.GridView grdResults;
		
		protected System.Web.UI.WebControls.HyperLink lnk;
	}
}
